FROM debian:stretch

LABEL maintainer="mgeitz" \
      version="0.1.1" \
      description="This image is used to start the tbdchat client executable"

RUN apt-get update -y && apt-get install -y \
    build-essential \
    libncurses5-dev \
    libssl1.0-dev

WORKDIR /bin/tbdc

COPY client/ client/

COPY Makefile .

RUN make chat_client

CMD ./tbdchat
